---
title: Multiperiod Optimization with Gurobi
author: ''
date: '2018-01-07'
slug: multiperiod-optimization-with-gurobi
summary: "Learn how to perform multiperiod linear optimization with Gurobi-python"
categories:
  - prescriptive analytics
tags:
  - Linear programming
  - Multiperiod Optimization
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

This is a simple example of multiperiod programming. The question was also derived from **Optimization in Operations Research** by *Rardin*. The question reads:

*Ace Green Windows (AGW) manufactures environmentally efficient windows as replacements of those in existing homes. It has just received a contract for the next 6 months, requiring 100, 250, 190, 140, 220, and 110 units in months 1 through 6, respectively. Production costs for windows vary with time due to the specialized materials. AGW estimates production will cost* $\text{\$250, \$450,\$350, \$400, \$520, and \$500}$ *per unit in periods 1 through 6, respectively. To take advantage of cost variations, AGW may produce more windows than the contract requires in some months and hold up to 375 of them in inventory for later months. But holding inventory costs $30 per window per month. Assume there is no beginning inventory.*

For simplicity let's assume that the months are from January to June. This creates the dimension of the problem. Let it be indexed by \textit{t}. Let the requirements for each month be denoted by $d_t$. Let the cost of production for each month be denoted by $p_t$.

The time-phased linear optimization model can be written as:

$$\sum_{t = Jan}^{Jun} p_t x_t + 30 \sum_{t = Jan}^{Jun} h_t$$ 

**Subject to:**

$$ h_{t-1} + x_t = d_t + h_t \quad \forall \quad t = 1,..6;  ....(1) $$

$$ h_t \leq 375 \quad \forall \quad t = 1,..6; ....(2)$$

$$ h_t, x_t \geq 0 \quad ....(3)$$

The first constraint defines the relationship between closing inventory from last period, current production and the current inventory with the present demand. The second constraint follows from the instruction in the question allowing an upper bound on the holding inventory to go beyond the required for every month. Lastly, we assume both are non negative.

We should take care while interpreting the first constraint in the opening and closing months. For January $h_{t-1}$ is just 0 while for the closing month in June, the $h_t$ is zero thereby reassuring the remaining inventory from May and current production from June equals current requirement for June and there are no left-over windows.

Here's the solution in Python:

```{python}
from gurobipy import *
m = Model('Window Inventory')

#create dimensions of the problem
calender = ['Jan','Feb','Mar','Apr','May','Jun'] #will be indexed by t

#monthly requirements
requirements = {'Jan':100,
                'Feb':250,
                'Mar':190,
                'Apr':140,
                'May':220,
                'Jun':110}

# production costs
prod_cost =    {'Jan':250,
                'Feb':450,
                'Mar':350,
                'Apr':400,
                'May':520,
                'Jun':500}
                
                
#create decision variables

#units produced in month t
produced = {}

for t in calender:
    produced[t] = m.addVar(lb = 0, vtype = GRB.CONTINUOUS, name = 'produced_%s'%(t))

# units held at time t
held = {}
for t in calender:
    held[t] = m.addVar(lb = 0, ub = 375, vtype = GRB.CONTINUOUS, name = 'held_%s'%(t))
    
m.update()

#set the objective
obj1 = quicksum( produced[t]*prod_cost[t] for t in calender )
obj2 = 30*quicksum( held[t] for t in calender )
obj = obj1 + obj2
m.setObjective(obj)

#define constraints

#beginning inventory + production amount - ending inventory = demand
#begining inventory + production amount = demand + ending inventory


#initial balance
m.addConstr(produced['Jan'] == requirements['Jan']+held['Jan'], 'inital')

#closing balance
m.addConstr(produced['Jun']+held['May'] == requirements['Jun'], 'closing')

# remaining balances
for t in calender:
    if t != calender[0] and t != calender[5]:
        m.addConstr(held[calender[calender.index(t) -1]]+produced[t] == requirements[t]+held[t], 'remaining')
        
m.optimize()

if m.status == GRB.status.OPTIMAL:
    print('\nMinimum objective is :',m.objval)


if m.status == GRB.status.OPTIMAL:
    print ('\nOptimal inventory :')
    for t in calender:
        print('produced at '+ str(t) + ': ' + str(produced[t].x))
        print('held at ' + str(t) + ': ' + str(held[t].x))
```


The output gives the optimal or minimal cost of inventory and production at $\$ 350200$. The company does make use of the variable production cost specifically in the months of January and March when they also hold the maximum specified inventory. This allows the company to store more and produce less (almost 0) during the ending months when the production costs are higher.
